package sri.playground.web

import org.scalajs.dom
import org.scalajs.dom.raw.DOMParser
import sri.playground.web.RawData._
import sri.playground.web.router.AppRouter
import sri.web.ReactDOM
import sri.playground.web.vdom._
import scala.scalajs.js.JSApp
import scala.scalajs.js.annotation.JSExport

object WebApp extends JSApp {


  @JSExport
  override def main(): Unit = {

    ReactDOM.render(AppRouter.router, dom.document.getElementById("app"))
    dom.window.console.log("",VDOM2.tbody(id = "hello")())
    dom.window.console.log("",VDOM2.del()())
    dom.window.console.log("",VDOM2.pre()())
    dom.window.console.log("",VDOM2.bdo()())
    dom.window.console.log("",VDOM2.textarea()())
    dom.window.console.log("",VDOM2.thead()())
    dom.window.console.log("",VDOM2.figcaption()())
    dom.window.console.log("",VDOM2.s()())
    dom.window.console.log("",VDOM2.ol()())
    dom.window.console.log("",VDOM2.span()())
    dom.window.console.log("",VDOM2.body()())
    dom.window.console.log("",VDOM2.area()())
    dom.window.console.log("",VDOM2.menu()())
    dom.window.console.log("",VDOM2.hr()())
    dom.window.console.log("",VDOM2.h4()())
    dom.window.console.log("",VDOM2.source()())
    dom.window.console.log("",VDOM2.h3()())
    dom.window.console.log("",VDOM2.dt()())
    dom.window.console.log("",VDOM2.map()())
    dom.window.console.log("",VDOM2.nav()())
    dom.window.console.log("",VDOM2.abbr()())
    dom.window.console.log("",VDOM2.samp()())
    dom.window.console.log("",VDOM2.li()())
    dom.window.console.log("",VDOM2.style()())
    dom.window.console.log("",VDOM2.param()())
    dom.window.console.log("",VDOM2.meter()())
    dom.window.console.log("",VDOM2.br()())
    dom.window.console.log("",VDOM2.big()())
    dom.window.console.log("",VDOM2.hgroup()())
    dom.window.console.log("",VDOM2.head()())
    dom.window.console.log("",VDOM2.u()())
    dom.window.console.log("",VDOM2.dfn()())
    dom.window.console.log("",VDOM2.img())
    dom.window.console.log("",VDOM2.data()())
    dom.window.console.log("",VDOM2.optgroup()())
    dom.window.console.log("",VDOM2.audio()())
    dom.window.console.log("",VDOM2.ul()())
    dom.window.console.log("",VDOM2.track()())
    dom.window.console.log("",VDOM2.label()())
    dom.window.console.log("",VDOM2.option()())
    dom.window.console.log("",VDOM2.a()())
    dom.window.console.log("",VDOM2.div()())
    dom.window.console.log("",VDOM2.rt()())
    dom.window.console.log("",VDOM2.article()())
    dom.window.console.log("",VDOM2.strong()())
    dom.window.console.log("",VDOM2.wbr()())
    dom.window.console.log("",VDOM2.main()())
    dom.window.console.log("",VDOM2.embed()())
    dom.window.console.log("",VDOM2.legend()())
    dom.window.console.log("",VDOM2.section()())
    dom.window.console.log("",VDOM2.i()())
    dom.window.console.log("",VDOM2.`object`()())
    dom.window.console.log("",VDOM2.fieldset()())
    dom.window.console.log("",VDOM2.base()())
    dom.window.console.log("",VDOM2.code()())
    dom.window.console.log("",VDOM2.ins()())
    dom.window.console.log("",VDOM2.h2()())
    dom.window.console.log("",VDOM2.td()())
    dom.window.console.log("",VDOM2.datalist()())
    dom.window.console.log("",VDOM2.select()())
    dom.window.console.log("",VDOM2.small()())
    dom.window.console.log("",VDOM2.aside()())
    dom.window.console.log("",VDOM2.em()())
    dom.window.console.log("",VDOM2.button()())
    dom.window.console.log("",VDOM2.rp()())
    dom.window.console.log("",VDOM2.dl()())
    dom.window.console.log("",VDOM2.th()())
    dom.window.console.log("",VDOM2.tfoot()())
    dom.window.console.log("",VDOM2.meta()())
    dom.window.console.log("",VDOM2.q()())
    dom.window.console.log("",VDOM2.tr()())
    dom.window.console.log("",VDOM2.b()())
    dom.window.console.log("",VDOM2.cite()())
    dom.window.console.log("",VDOM2.blockquote()())
    dom.window.console.log("",VDOM2.progress()())
    dom.window.console.log("",VDOM2.col()())
    dom.window.console.log("",VDOM2.video()())
    dom.window.console.log("",VDOM2.caption()())
    dom.window.console.log("",VDOM2.noscript()())
    dom.window.console.log("",VDOM2.link()())
    dom.window.console.log("",VDOM2.menuitem()())
    dom.window.console.log("",VDOM2.p()())
    dom.window.console.log("",VDOM2.h6()())
    dom.window.console.log("",VDOM2.iframe()())
    dom.window.console.log("",VDOM2.h1()())
    dom.window.console.log("",VDOM2.keygen()())
    dom.window.console.log("",VDOM2.address()())
    dom.window.console.log("",VDOM2.details()())
    dom.window.console.log("",VDOM2.picture()())
    dom.window.console.log("",VDOM2.header()())
    dom.window.console.log("",VDOM2.sub()())
    dom.window.console.log("",VDOM2.time()())
    dom.window.console.log("",VDOM2.script()())
    dom.window.console.log("",VDOM2.title()())
    dom.window.console.log("",VDOM2.output()())
    dom.window.console.log("",VDOM2.figure()())
    dom.window.console.log("",VDOM2.form()())
    dom.window.console.log("",VDOM2.html()())
    dom.window.console.log("",VDOM2.ruby()())
    dom.window.console.log("",VDOM2.mark()())
    dom.window.console.log("",VDOM2.bdi()())
    dom.window.console.log("",VDOM2.kbd()())
    dom.window.console.log("",VDOM2.sup()())
    dom.window.console.log("",VDOM2.h5()())
    dom.window.console.log("",VDOM2.footer()())
    dom.window.console.log("",VDOM2.input())
    dom.window.console.log("",VDOM2.summary()())
    dom.window.console.log("",VDOM2.dialog()())
    dom.window.console.log("",VDOM2.`var`()())
    dom.window.console.log("",VDOM2.canvas()())
    dom.window.console.log("",VDOM2.table()())
    dom.window.console.log("",VDOM2.colgroup()())
    dom.window.console.log("sf",VDOM2.dd()())

  }

}
